<?php

namespace AppBundle\Repository;

/**
 * ThreatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreatRepository extends \Doctrine\ORM\EntityRepository
{
}
